--
-- pg_get_table_ddl
--
-- All tests pass owner=>false so the ALTER TABLE OWNER TO line is not
-- emitted, keeping output stable across test runners (which may run under
-- different role names).
--
CREATE SCHEMA pgtbl_ddl_test;
SET search_path = pgtbl_ddl_test;

-- Basic table with PRIMARY KEY, NOT NULL, DEFAULT, COLLATE.
CREATE TABLE basic (
    id int PRIMARY KEY,
    name text NOT NULL DEFAULT 'anon' COLLATE "C"
);
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'owner', 'false');

-- Identity columns (with default and custom sequence options).
CREATE TABLE id_cols (
    id_always int GENERATED ALWAYS AS IDENTITY,
    id_default int GENERATED BY DEFAULT AS IDENTITY
);
SELECT * FROM pg_get_table_ddl('id_cols'::regclass, 'owner', 'false');

CREATE TABLE id_custom (
    v int GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME id_custom_v_seq
        START WITH 100 INCREMENT BY 5
        MINVALUE 50 MAXVALUE 1000
        CACHE 10 CYCLE
    )
);
SELECT * FROM pg_get_table_ddl('id_custom'::regclass, 'owner', 'false');

-- Generated stored column.
CREATE TABLE gen_cols (
    cents int,
    dollars numeric GENERATED ALWAYS AS (cents / 100.0) STORED
);
SELECT * FROM pg_get_table_ddl('gen_cols'::regclass, 'owner', 'false');

-- STORAGE and COMPRESSION (only emitted when non-default for the type).
CREATE TABLE storage_cols (
    a text STORAGE EXTERNAL,
    b text STORAGE MAIN,
    c text COMPRESSION pglz
);
SELECT * FROM pg_get_table_ddl('storage_cols'::regclass, 'owner', 'false');

-- Constraints: CHECK, UNIQUE, FOREIGN KEY (DEFERRABLE).
CREATE TABLE refd (id int PRIMARY KEY);
CREATE TABLE cons (
    a int CHECK (a > 0),
    b int UNIQUE,
    c int REFERENCES refd(id) DEFERRABLE INITIALLY DEFERRED
);
SELECT * FROM pg_get_table_ddl('cons'::regclass, 'owner', 'false');

-- Indexes: functional and partial.  Constraint-backing indexes are
-- suppressed (they are emitted by the constraint loop).
CREATE TABLE idxd (id int PRIMARY KEY, name text);
CREATE INDEX idxd_lower ON idxd (lower(name));
CREATE INDEX idxd_partial ON idxd (id) WHERE id > 100;
SELECT * FROM pg_get_table_ddl('idxd'::regclass, 'owner', 'false');

-- Inheritance, including a child DEFAULT override on an inherited column.
CREATE TABLE par (a int DEFAULT 1, b text);
CREATE TABLE ch (c int) INHERITS (par);
ALTER TABLE ch ALTER COLUMN a SET DEFAULT 999;
SELECT * FROM pg_get_table_ddl('ch'::regclass, 'owner', 'false');

-- Per-column attoptions: emitted as ALTER COLUMN SET (...).
CREATE TABLE attopt (a int, b text);
ALTER TABLE attopt ALTER COLUMN a SET (n_distinct = 100);
SELECT * FROM pg_get_table_ddl('attopt'::regclass, 'owner', 'false');

-- Partitioned table parent (RANGE and HASH).
CREATE TABLE parted_range (id int, k int) PARTITION BY RANGE (id);
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, 'owner', 'false');

CREATE TABLE parted_hash (id int) PARTITION BY HASH (id);
SELECT * FROM pg_get_table_ddl('parted_hash'::regclass, 'owner', 'false');

-- Partition children: FROM/TO, WITH (modulus, remainder), DEFAULT.
CREATE TABLE parted_range_1 PARTITION OF parted_range
    FOR VALUES FROM (0) TO (100);
ALTER TABLE parted_range_1 ALTER COLUMN k SET DEFAULT 7;
SELECT * FROM pg_get_table_ddl('parted_range_1'::regclass, 'owner', 'false');

CREATE TABLE parted_hash_0 PARTITION OF parted_hash
    FOR VALUES WITH (modulus 2, remainder 0);
SELECT * FROM pg_get_table_ddl('parted_hash_0'::regclass, 'owner', 'false');

CREATE TABLE parted_range_def PARTITION OF parted_range DEFAULT;
SELECT * FROM pg_get_table_ddl('parted_range_def'::regclass, 'owner', 'false');

-- Rules.
CREATE TABLE rt (id int);
CREATE TABLE rt_log (id int);
CREATE RULE rt_log_insert AS ON INSERT TO rt
    DO ALSO INSERT INTO rt_log VALUES (NEW.id);
SELECT * FROM pg_get_table_ddl('rt'::regclass, 'owner', 'false');

-- Extended statistics.
CREATE TABLE stx (a int, b int, c int);
CREATE STATISTICS stx_ndv (ndistinct) ON a, b FROM stx;
SELECT * FROM pg_get_table_ddl('stx'::regclass, 'owner', 'false');

-- Row-level security toggles.
CREATE TABLE rls (id int);
ALTER TABLE rls ENABLE ROW LEVEL SECURITY;
ALTER TABLE rls FORCE ROW LEVEL SECURITY;
SELECT * FROM pg_get_table_ddl('rls'::regclass, 'owner', 'false');

-- REPLICA IDENTITY: emitted only when not the default.
CREATE TABLE ri_full (a int);
ALTER TABLE ri_full REPLICA IDENTITY FULL;
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, 'owner', 'false');

CREATE TABLE ri_idx (a int NOT NULL);
CREATE UNIQUE INDEX ri_idx_a ON ri_idx (a);
ALTER TABLE ri_idx REPLICA IDENTITY USING INDEX ri_idx_a;
SELECT * FROM pg_get_table_ddl('ri_idx'::regclass, 'owner', 'false');

-- UNLOGGED + reloptions.
CREATE UNLOGGED TABLE uno (id int) WITH (fillfactor = 70);
SELECT * FROM pg_get_table_ddl('uno'::regclass, 'owner', 'false');

-- Pretty mode.
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'owner', 'false', 'pretty', 'true');

-- Error: not an ordinary or partitioned table.
CREATE VIEW v AS SELECT 1 AS x;
SELECT * FROM pg_get_table_ddl('v'::regclass);

CREATE SEQUENCE s;
SELECT * FROM pg_get_table_ddl('s'::regclass);

-- NULL argument returns no rows.
SELECT * FROM pg_get_table_ddl(NULL);

-- Unrecognized option.
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'bogus', 'true');

-- Odd number of variadic args.
SELECT * FROM pg_get_table_ddl('basic'::regclass, 'pretty');

-- Cleanup.
DROP SCHEMA pgtbl_ddl_test CASCADE;
